name: Domain Configuration UI
description: 'Allows saving of domain specific configuration through the administrative interface.'
type: module
package: Domain
core_version_requirement: ^10.2 || ^11
configure: domain_config_ui.settings
dependencies:
  - domain:domain_config

# Information added by Drupal.org packaging script on 2026-02-04
version: '2.0.0-rc2'
project: 'domain'
datestamp: 1770210889
